name: forest_carbon
version: '0.1.0'
config-version: 2

profile: forest_carbon

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  forest_carbon:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
